[[processes]]
name = "hello"
pre = "/bin/echo Hello {{USER}}! How are you today?"

[[processes]]
name = "php"
run = [ "php", "-S", "0.0.0.0:9000" ]

[[processes]]
name = "nginx"
run = [ "/usr/sbin/nginx", "-g", "daemon off; user nobody;" ]
